# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@ContentType = application/json
@Authorization = Bearer {{login.response.body.token}}

GET http://{{host}}
###
GET http://{{host}}/asd
###

# @name login
POST http://{{host}}/auth
Content-Type: {{ContentType}}

{
  "password": "password",
  "email": "asd@asd.com"
}

###
# @name list-users
GET http://{{host}}/user?page=34&size=3
Authorization: {{Authorization}}
###
# @name create-user
POST http://{{host}}/user
Content-Type: {{ContentType}}

{
  "name": "Joe Doe",
  "password": "password",
  "email": "asd@asd.com"
}
###
# @name get-user
GET http://{{host}}/user/103
Authorization: {{Authorization}}
###
# @name update-user
POST http://{{host}}/user/103
Authorization: {{Authorization}}
Content-Type: {{ContentType}}

{
  "name": "Another Name"
}
###
# @name delete-user
DELETE  http://{{host}}/user/105
Authorization: {{Authorization}}
###
