version: "3.6"

services:
  api:
    image: rest-api:latest
    container_name: rest-api
    restart: unless-stopped
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      NODE_PATH: .
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000"]
      interval: 1m
      timeout: 5s
      retries: 30

  db:
    image: mysql
    container_name: rest-api_db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - rest-api_data:/var/lib/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--host=127.0.0.1",
          "--password=$$MYSQL_PASSWORD",
        ]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer:latest
    container_name: rest-api_adminer
    restart: unless-stopped
    environment:
      ADMINER_DESIGN: konya
    ports:
      - 8888:8080

volumes:
  rest-api_data:
