app:
  port: 3000
  host: 0.0.0.0
  jwt:
    secret: vewyvewysecret
    options:
      expiresIn: 12h
      algorithm: HS512
  hash:
    digest: whirlpool
    iterations: 1000
    keylen: 64
redis:
  host: redis
  port: 6379
database:
  dialect: mysql
  host: localhost
  database: default
  port: 3306
  pool:
    min: 0
    max: 10
  define:
    underscored: true
    timestamps: true
    paranoid: true
