name: build & test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install & build
        run: |
          yarn
          CI=false yarn build
      - name: run tests
        run: yarn test
